[RFC] Support `torch.distributed.distributed_c10d.all_reduce` (PR702)
* Init

Currently `all_reduce` gets ignored. I need a way to tell preprocessing
that certain group of operations look inplace but have efffects on
inputs. Thus ignoring them breaks the semantic of program.

Example:
```python
import os

import torch
import torch.distributed.distributed_c10d as c10d

import thunder
from thunder.executors import Executor

def f(x, y, process_group: c10d.ProcessGroup):
    z = x + y
    c10d.all_reduce(z, group=process_group)
    w = z + 1
    return x, w

if __name__ == "__main__":
    local_rank = int(os.environ["LOCAL_RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    torch.distributed.init_process_group(backend="nccl")

    x, y = [torch.tensor(1.0).cuda(local_rank) for _ in range(2)]
    default_process_group = c10d._get_default_group()
    process_group = c10d.new_group()

    c_f = thunder.compile(f, executors_list=[Executor.TORCH])
    _ = c_f(x, y, process_group)

    for t in thunder.last_traces(c_f)[:3]:
        print(t)
```

The output of `torchrun --nproc-per-node=1 sample.py` is as follows:
```python
import torch

@torch.no_grad()
def thunder_140183539187424(x, y, process_group):
  PR x: "cuda:0 f32[]" =  x  (trivial unpack)
  PR y: "cuda:0 f32[]" =  y  (trivial unpack)
  PR _torch_distributed_distributed_c10d_ProcessGroup_1 =
_torch_distributed_distributed_c10d_ProcessGroup_1  (trivial unpack)
  t0 = ltorch.add(x, y)  PR t0: "cuda:0 f32[]"
    PR t0 = prims.add(x, y)  PR t0: "cuda:0 f32[]"
  t1 = ltorch.all_reduce(t0,
group=_torch_distributed_distributed_c10d_ProcessGroup_1)  PR t1: "cuda:0
f32[]"
    PR t1 = prims.all_reduce(t0,
_torch__C__distributed_c10d_ReduceOp_RedOpType_2,
_torch_distributed_distributed_c10d_ProcessGroup_1, False)  PR t1:
"cuda:0 f32[]"
  t2 = ltorch.add(t0, 1)  PR t2: "cuda:0 f32[]"
    PR _ = prims.convert_element_type(1, float)
    PR t2 = prims.add(t0, 1.0)  PR t2: "cuda:0 f32[]"
  return (x, t2)
```

As in the above, `t2`'s right-hand side should be `ltorch.add(t1, 1)`
but actually is `ltorch.add(t0, 1)`, which is wrong. As I run this with
only one GPU, the result woudl be the same but in general, not.

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

* return None following pytorch and update DCE deny list

```
Traceback (most recent call last):
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/sand_pit/all_reduce_init.py",
line 28, in <module>
    _ = c_f(x, y, process_group)
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/__init__.py",
line 385, in _fn
    extrace, extraces = executors.transform_for_execution(
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/executors/__init__.py",
line 155, in transform_for_execution
    fused_trace, fused_traces = passes.fuse(postflatten_dce_trace)
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/executors/passes.py",
line 327, in fuse
    _fuse_region_with_executor(ex, region)
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/executors/passes.py",
line 312, in _fuse_region_with_executor
    fused_bsyms.extend(executor.fuse(region_fuse))
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/executors/torchex.py",
line 1193, in fuse
    tbsym = translator(bsym, *bsym.args, **bsym.kwargs)
TypeError: all_reduce() missing 1 required positional argument: 'op'
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

* Tracing seems to be working only with torch executor

for the following script:
```python
import os

import torch
import torch.distributed.distributed_c10d as c10d

import thunder
from thunder.executors import Executor

def f(x, y, process_group: c10d.ProcessGroup):
    z = x + y
    c10d.all_reduce(z, c10d.ReduceOp.SUM, group=process_group)
    w = z + 1
    return x, w

if __name__ == "__main__":
    local_rank = int(os.environ["LOCAL_RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    torch.distributed.init_process_group(backend="nccl")

    x, y = [torch.tensor(1.0).cuda(local_rank) for _ in range(2)]
    default_process_group = c10d._get_default_group()
    process_group = c10d.new_group()

    c_f = thunder.compile(f, executors_list=[Executor.TORCH])
    _ = c_f(x, y, process_group)

    for t in thunder.last_traces(c_f):
        print(t)
```

with the final trace of
```
torch.distributed.distributed_c10d
import torch

@torch.no_grad()
def thunder_139893940719280(x, y, process_group):
  PR x: "cuda:0 f32[]" =  x  (trivial unpack)
  PR y: "cuda:0 f32[]" =  y  (trivial unpack)
  PR _torch_distributed_distributed_c10d_ProcessGroup_0 =
_torch_distributed_distributed_c10d_ProcessGroup_0  (trivial unpack)
  t0 = torch.add(x, y)  PR t0: "cuda:0 f32[]"
  del [y]
  torch.distributed.distributed_c10d.all_reduce(t0,
_torch__C__distributed_c10d_ReduceOp_RedOpType_1,
_torch_distributed_distributed_c10d_ProcessGroup_0, False)
  t1 = torch.add(t0, 1)  PR t1: "cuda:0 f32[]"
  del [t0]
  return (x, t1)
```

If nvfuser is enabled, the final trace loses the semantics as follows
```
torch.distributed.distributed_c10d
import torch

@torch.no_grad()
def thunder_140673289129024(x, y, process_group):
  PR x: "cuda:0 f32[]" =  x  (trivial unpack)
  PR y: "cuda:0 f32[]" =  y  (trivial unpack)
  PR _torch_distributed_distributed_c10d_ProcessGroup_0 =
_torch_distributed_distributed_c10d_ProcessGroup_0  (trivial unpack)
  (t0, t1) = nvFusion0(x, y)
    PR t0 = prims.add(x, y)  PR t0: "cuda:0 f32[]"
    PR t1 = prims.add(t0, 1.0)  PR t1: "cuda:0 f32[]"
  del [y]
  torch.distributed.distributed_c10d.all_reduce(t0,
_torch__C__distributed_c10d_ReduceOp_RedOpType_1,
_torch_distributed_distributed_c10d_ProcessGroup_0, False)
  del [t0]
  return (x, t1)
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

* return tensor in bsym and prim of `all_reduce`

Co-authored-by: Ivan Yashchuk <IvanYashchuk@users.noreply.github.com>

* Revert "return tensor in bsym and prim of `all_reduce`"

This reverts commit 3cc522907da6d565d7a5a6a4df292271cab4eb66.

```python
import os

import torch
import torch.distributed.distributed_c10d as c10d

import thunder
from thunder.executors import Executor

def f(x, y, process_group: c10d.ProcessGroup):
    z = x + y
    c10d.all_reduce(z, c10d.ReduceOp.AVG, group=process_group)
    w = z + 1
    return x, w

if __name__ == "__main__":
    local_rank = int(os.environ["LOCAL_RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    torch.distributed.init_process_group(backend="nccl")

    x, y = [torch.tensor(1.0).cuda(local_rank) for _ in range(2)]
    default_process_group = c10d._get_default_group()
    process_group = c10d.new_group()

    c_f = thunder.compile(f, executors_list=[Executor.TORCH])  PR ,
Executor.NVFUSER])
    _ = c_f(x, y, process_group)

    for t in thunder.last_traces(c_f):
        print(t)
```

```
Traceback (most recent call last):
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/all_reduce.py",
line 27, in <module>
    _ = c_f(x, y, process_group)
  File
"/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/__init__.py",
line 405, in _fn
    result: Any = c(*args, **kwargs)
  File
"/home/mkozuki/ghq/github.com/pytorch/pytorch/torch/utils/_contextlib.py",
line 115, in decorate_context
    return func(*args, **kwargs)
  File "LC.gen_0", line 14, in thunder_139793600924928
TypeError: add(): argument 'input' (position 1) must be Tensor, not
NoneType
```

* add test

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

* check nvfuser availability

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

* mention unwanted reorder of collectives with nvfuser executor

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>

* functional all_reduce

* tweaks

* test improvement per review

---------

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>
Co-authored-by: Ivan Yashchuk <IvanYashchuk@users.noreply.github.com>
Co-authored-by: Mike Ruberry <mike.ruberry@lightning.ai>