Register augmented forward and backward
But, the backward is failing when parameter lifting is involved:
```
Traceback (most recent call last):
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/./torch_compile_compliant_custom_ops.py", line 173, in <module>
    out.backward(torch.ones_like(out))
  File "/home/mkozuki/ghq/github.com/crcrpar/torch-2/torch/_tensor.py", line 653, in backward
    torch.autograd.backward(
  File "/home/mkozuki/ghq/github.com/crcrpar/torch-2/torch/autograd/__init__.py", line 354, in backward
    _engine_run_backward(
  File "/home/mkozuki/ghq/github.com/crcrpar/torch-2/torch/autograd/graph.py", line 829, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

The current implementation works correctly with this kind of module free
from parameter lifting
```python
class MyModul(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 2, bias=False)

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        h = torch.ops.my_custom_op.mul(x, y)
        activation = torch.relu(h)
        out = torch.sin(activation)
        return out
```
but not with ones with parameter lifting e.g.
```python
class MyModul(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 2, bias=False)

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        h = torch.ops.my_custom_op.mul(x, y)
        activation = torch.relu(h)
        out = self.linear(activation)
        return out
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>