Check `last_backward_traces` availability
by adding availability check of grads and backward traces.

While investigating the performance gap between
`thunder.dynamo.compiler.thunderfx` and `torch.compile` as a compiler
backend of vLLM V1 (I was using Qwen2.5 3B for single H100 and 72B for
8 H100s), I saved all the `torch.fx.GraphModule`s to run
`thunder.dynamo.report.thunderfx_benchmark_report` for better
understanding of the perf gap. As I set `disable_torch_autograd=True`,
it'd be expected that there's no backward traces but the lines that are
changed in this commit expects backward traces to be always available:

```console
Traceback (most recent call last):
  File "/opt/vllm/vllm-src/thunderfx_graph_inputs/graph_0.py", line 185, in <module>
    thunderfx_benchmark_report(
  File "/usr/local/lib/python3.12/dist-packages/lightning_thunder-0.2.2.dev0-py3.12.egg/thunder/dynamo/report.py", line 1221, in thunderfx_benchmark_report
    thunderfx_benchmark_report_from_splits(
  File "/usr/local/lib/python3.12/dist-packages/lightning_thunder-0.2.2.dev0-py3.12.egg/thunder/dynamo/report.py", line 1157, in thunderfx_benchmark_report_from_splits
    make_nvfusion_reports(runnable_split_reports)
  File "/usr/local/lib/python3.12/dist-packages/lightning_thunder-0.2.2.dev0-py3.12.egg/thunder/dynamo/report.py", line 1114, in make_nvfusion_reports
    split_report.create_fusion_reports()
  File "/usr/local/lib/python3.12/dist-packages/lightning_thunder-0.2.2.dev0-py3.12.egg/thunder/dynamo/report.py", line 728, in create_fusion_reports
    self._create_thunder_traces()
  File "/usr/local/lib/python3.12/dist-packages/lightning_thunder-0.2.2.dev0-py3.12.egg/thunder/dynamo/report.py", line 721, in _create_thunder_traces
    self.bwd_trc = bwd_traces[-1]
                   ~~~~~~~~~~^^^^
IndexError: list index out of range
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>