Remove `import thunder.core.transforms` from `thunder/core/jit_ext.py`
to fix:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/runner/work/lightning-thunder/lightning-thunder/docs/source/conf.py", line 418, in <module>
    import thunder  # noqa: E402 # making the docs build happy
  File "/home/runner/work/lightning-thunder/lightning-thunder/thunder/__init__.py", line 77, in <module>
    from thunder.core.jit_ext import thunder_general_jit
  File "/home/runner/work/lightning-thunder/lightning-thunder/thunder/core/jit_ext.py", line 33, in <module>
    import thunder.core.transforms
  File "/home/runner/work/lightning-thunder/lightning-thunder/thunder/core/transforms.py", line 77, in <module>
    import thunder.torch as ltorch
  File "/home/runner/work/lightning-thunder/lightning-thunder/thunder/torch/__init__.py", line 29, in <module>
    import thunder.distributed.prims as dist_prims
  File "/home/runner/work/lightning-thunder/lightning-thunder/thunder/distributed/prims.py", line 13, in <module>
    from thunder.core.transforms import register_augmented_forward, register_backward
ImportError: cannot import name 'register_augmented_forward' from partially initialized module 'thunder.core.transforms' (most likely due to a circular import) (/home/runner/work/lightning-thunder/lightning-thunder/thunder/core/transforms.py)
```

I see this by running `python -c 'import torch; import thunder'`

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>