Re-enable vjp tests in test_core.py (PR439)
* Remove xfails for eval_trace tests

* Hide returning proxies under unsafe flag

* Ignore unpacking prims in eval_trace

* Fix flatten_func

* Enable test_transforms_vjp_1_2

* Enable test_transforms_vjp_2_2_kwarg

* Enable test_transforms_vjp_2_1; enabled decomposed_fn_aug_fwd_rule

* Enable test_transforms_vmap_inline_value_and_grad

* Revert "Hide returning proxies under unsafe flag"

This reverts commit d9f4b76744ac30368f795fc66c7927ed70f63a8c.

* Fix AttributeError: 'NoneType' object has no attribute 'supports_devicetype'